"use client";
import { useState } from "react";
import { deterministicSummary, reportData } from "@/lib/report-data";

type Report = typeof reportData & { summary: string; narrativeMode: string };
const fmt = (n:number) => new Intl.NumberFormat("en-US",{maximumFractionDigits:0}).format(n);

export default function Page(){
 const [report,setReport]=useState<Report|null>(null); const [loading,setLoading]=useState(false); const [step,setStep]=useState(0);
 const stages=["Running governed SQL","Validating KPI payload","Identifying material changes","Generating executive narrative"];
 async function generate(){setLoading(true);setStep(0);const timer=setInterval(()=>setStep(s=>Math.min(s+1,3)),650);try{const r=await fetch("/api/report",{method:"POST"});setReport(await r.json())}catch{setReport({...reportData,summary:deterministicSummary(),narrativeMode:"validated-fallback"})}finally{clearInterval(timer);setLoading(false)}}
 const d=report;
 return <div className="shell"><aside><div className="brand"><i/>Northstar</div><p>BUSINESS INTELLIGENCE</p><nav><b>Monthly review</b><span>Performance trends</span><span>Market analysis</span><span>Report archive</span></nav><footer>CONTROLLED ANALYTICS<br/>Databricks-calculated<br/>AI-explained</footer></aside><main><header><div><h1>Monthly Business Review</h1><p>Decision-ready performance intelligence, grounded in governed data.</p></div><div className="actions"><select aria-label="Report month"><option>December 2014</option></select><button onClick={generate} disabled={loading}>{loading?"Generating…":"Generate report →"}</button></div></header>{loading&&<div className="progress"><i/><b>{stages[step]}</b><span>Step {step+1} of 4</span></div>}{!d?<div className="empty">Select a reporting period and generate the executive report.</div>:<ReportView d={d}/>}</main></div>
}

function ReportView({d}:{d:Report}){const c=d.current,max=Math.max(...d.trend.map(x=>x.sales));return <section className="report"><div className="reportHead"><div><small>EXECUTIVE PERFORMANCE REPORT</small><h2>December 2014</h2></div><em>✓ DATA VALIDATED</em></div><div className="kpis"><Kpi label="Reported sales" value={fmt(c.sales)} delta={c.salesMom}/><Kpi label="Reported profit" value={fmt(c.profit)} delta={c.profitMom}/><Kpi label="Logical orders" value={fmt(c.orders)} delta={c.ordersMom}/><div className="card kpi"><label>Profit margin</label><strong>{c.margin.toFixed(1)}%</strong><span>{fmt(c.units)} units sold</span></div></div><div className="heroGrid"><div className="card"><h3>Sales trajectory</h3><div className="bars">{d.trend.map(x=><div key={x.month} style={{height:`${x.sales/max*100}%`}} title={`${x.month}: ${fmt(x.sales)}`}/>)}</div><div className="axis"><span>Sep 2014</span><span>Dec 2014</span></div></div><article className="card summary"><small>EXECUTIVE SUMMARY · {d.narrativeMode}</small><p>{d.summary}</p><footer>Every number is sourced from the validated KPI payload.</footer></article></div><div className="tables"><DataTable title="Market performance" rows={d.markets}/><DataTable title="Category performance" rows={d.categories}/><DataTable title="Target watchlist" rows={d.targets}/><DataTable title="Profit exceptions" rows={d.exceptions}/></div></section>}
function Kpi({label,value,delta}:{label:string,value:string,delta:number}){return <div className="card kpi"><label>{label}</label><strong>{value}</strong><span className={delta>=0?"positive":"negative"}>{delta>=0?"+":""}{delta.toFixed(1)}% vs prior month</span></div>}
function DataTable({title,rows}:{title:string,rows:readonly (readonly (string|number)[])[]}){return <div className="card table"><h3>{title}</h3>{rows.map((r,i)=><div className="row" key={i}><span><b>{r[0]}</b><small>{r[1]}</small></span><span>{typeof r[2]==="number"?fmt(r[2]):r[2]}</span><span className={Number(r[3])<0?"negative":""}>{typeof r[3]==="number"?fmt(r[3]):r[3]}</span><span>{r[4]!==undefined?`${r[4]}%`:""}</span></div>)}</div>}
